### ISSUE TITLE
utm 0.7.0 not available on conda-forge

### ISSUE THREAD

**Issue by johnflavin** [conda-forge/utm-feedstock#7]
UTM 0.7.0 does not exist on conda forge.

<details>
<pre>
conda search utm
Loading channels: done
# Name                       Version           Build  Channel
utm                            0.4.2          py27_0  conda-forge
utm                            0.4.2          py35_0  conda-forge
utm                            0.4.2          py36_0  conda-forge
utm                            0.5.0            py_0  conda-forge
utm                            0.6.0    pyh9f0ad1d_0  conda-forge
</pre>
</details>

It looks like there was an MR for it #4 but it failed to build: https://github.com/conda-forge/utm-feedstock/runs/1454082361.

**Comment by johnflavin** [comment]
@Turbo87 @snowman2

**Comment by snowman2** [comment]
@ocefpaf are you able to restart the failed azure pipeline?

**Comment by ocefpaf** [comment]
Argh. Missed this. Restarting now!

**Comment by ocefpaf** [comment]
Done: https://anaconda.org/conda-forge/utm/files?version=0.7.0

The CDN should sync in ~50 min and it will be available in the channel sortly.
